# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
